git:
  depth: false

sudo: required

language: python


install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements_dev.txt

script:
  - flake8 test


# branches:
#   only:
#     - "master"
