version: 2
jobs:
  build_and_test_onnx:
    machine: true
    working_directory: ~/ngraph-ci-test
    steps:
      - checkout
      - run:
          name: Build ONNX-Runtime docker image
          command: cd onnx-backend-scoreboard && docker build -t scoreboard/onnx -f runtimes/onnx-runtime/stable/Dockerfile .

      - run:
          name: Run docker image
          command: cd onnx-backend-scoreboard && docker run --name onnx-runtime -it -v ~/ngraph-ci-test/onnx-backend-scoreboard/results/onnx-runtime/stable:/root/results scoreboard/onnx || true

      - run:
          name: Commit results
          command: cd onnx-backend-scoreboard/results/onnx-runtime/stable && cat trend.json

      - deploy:
          name: Deploy results
          working_directory: ~/ngraph-ci-test/onnx-backend-scoreboard/results
          command: |
            # git config credential.helper 'cache --timeout=120'
            git config --global user.email "katarzyna.mitrus@intel.com"
            git config --global user.name "mitruska"

            git add .
            git commit -m "Scoreboard results"
            git push -f origin "mitruska/scoreboard:remotes/origin/mitruska/scoreboard"

  # build_and_test_ngraph:
  #   machine: true
  #   working_directory: ~/ngraph-ci-test
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build nGraph docker image
  #         command: cd onnx-backend-scoreboard && docker build -t scoreboard/ngraph -f runtimes/ngraph/development/Dockerfile .

  #     - run:
  #         name: Run nGraph docker image
  #         command: cd onnx-backend-scoreboard && docker run --name ngraph -it -v ~/ngraph-ci-test/onnx-backend-scoreboard/results/ngraph/development:/root/results scoreboard/ngraph || true

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test_onnx
      # - build_and_test_ngraph
