version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Build docker image
          command: docker build -t test_ngraph_onnx -f ../Dockerfile .

      - run:
          name: Run docker image
          command: docker run test_ngraph_onnx
